config/routes.rb
Rails.application.routes.draw do
  resources :externals
  resources :expenses
  resources :groups
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users
  root "sessions#new"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/external.rb
class External < ApplicationRecord
  belongs_to :user

  validates :name, :amount, presence: true

  def total_ex
    External.sum(:amount)
  end
end

app/controllers/externals_controller.rb
class ExternalsController < ApplicationController
  before_action :set_external, only: [:show, :edit, :update, :destroy]

  # GET /externals
  # GET /externals.json
  def index
    @externals = External.all.order("created_at DESC")
  end

  # GET /externals/1
  # GET /externals/1.json
  def show
  end

  # GET /externals/new
  def new
    @external = current_user.externals.build
  end

  # GET /externals/1/edit
  def edit
  end

  # POST /externals
  # POST /externals.json
  def create
    @external = current_user.externals.build(external_params)

    respond_to do |format|
      if @external.save
        format.html { redirect_to @external, notice: "External was successfully created." }
        format.json { render :show, status: :created, location: @external }
      else
        format.html { render :new }
        format.json { render json: @external.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /externals/1
  # PATCH/PUT /externals/1.json
  def update
    respond_to do |format|
      if @external.update(external_params)
        format.html { redirect_to @external, notice: "External was successfully updated." }
        format.json { render :show, status: :ok, location: @external }
      else
        format.html { render :edit }
        format.json { render json: @external.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /externals/1
  # DELETE /externals/1.json
  def destroy
    @external.destroy
    respond_to do |format|
      format.html { redirect_to externals_url, notice: "External was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_external
    @external = External.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def external_params
    params.require(:external).permit(:name, :amount)
  end
end

app/helpers/externals_helper.rb
module ExternalsHelper
end

app/views/externals/_form.html.erb
<%= form_with(model: external, local: true) do |form| %>
  <% if external.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(external.errors.count, "error") %> prohibited this external from being saved:</h2>

      <ul>
        <% external.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group m-2">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group m-2">
    <%= form.label :amount %>
    <%= form.number_field :amount, class: "form-control" %>
  </div>

  <div class="actions">
     <%= form.submit :Submit, class: "btn btn-success" %>
  </div>
<% end %>

app/views/externals/edit.html.erb
<h1>Editing External</h1>

<%= render 'form', external: @external %>

<%= link_to 'Show', @external %> |
<%= link_to 'Back', externals_path %>

app/views/externals/index.html.erb
<%= link_to "Add New", new_external_path, class: "btn btn-light m-2" %>
<div class="container bg-light">
  <div class="row alert alert-secondary">
     <div class="col-4">
    Total expenses
  </div>
   <div class="col-6">
    
  </div>
   <div class="col">
     <% @externals.first(1).each do |external| %>
    <p>$<%= external.total_ex %></p>
    <% end %>
  </div>
  </div>
  <hr>
  <% @externals.each do |external| %>

  <div class="row alert alert-secondary">
    <div class="col">
    <p>None</p>
    </div>
    <div class="col-6">
      <h3 class="text-muted"><%= external.name.capitalize %></h3><br>
      <p class="text-muted"><small><%= external.created_at.strftime("%B %d %Y, %l:%M%P") %></small></p>
    </div>
    <div class="col">
      <p>$<%= external.amount %></p><br>
      <% if current_user.id == external.user.id %>
      <%= link_to "Edit", edit_external_path(external) %>
      <%= link_to "Delete", external, method: :delete, data: { confirm: "Are you sure?" } %>
    <% end %>
    </div>
  </div>
  <% end %>
</div>

app/views/externals/new.html.erb
<h1>New External</h1>

<%= render 'form', external: @external %>

<%= link_to 'Back', externals_path %>

app/views/externals/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @external.name %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @external.amount %>
</p>

      <p class="text-muted"><small><%= @external.created_at.strftime("%B %d %Y, %l:%M%P") %></small></p>

<%= link_to "Back", externals_path, class: "btn btn-info m-2" %>