config/routes.rb
Rails.application.routes.draw do
  resources :externals
  resources :expenses
  resources :groups
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users
  root "sessions#new"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GroupTransactions</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
    <%= javascript_pack_tag "application", 'data-turbolinks-track': "reload" %>
  </head>

  <body class="bg-info">
  <p id="notice"><%= notice %></p>

  <nav class="navbar navbar-expand-lg navbar-dark static-top">
  <div class="container">
    <a class="navbar-brand" href="#">
          HomeExp
        </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <% if logged_in? %>
        <li class="nav-item">
          <%= link_to "Profile", user_path(current_user), class: "nav-link" %>
          </li>
          <li class="nav-item">
          <%= link_to "Log out", logout_path, method: :delete, class: "nav-link" %>
          </li>
          <% else %>
          <li class="nav-item">
          <%= link_to "Login", login_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
          <%= link_to "Sign Up", new_user_path, class: "nav-link" %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
    <%= yield %>
  </body>
</html>